// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrB38Xp7t3UAs4d_3djLDBBmRrqdlSwtM',
    appId: '1:698815211930:web:7253432605473686f27223',
    messagingSenderId: '698815211930',
    projectId: 'pet-care-app-2cd12',
    authDomain: 'pet-care-app-2cd12.firebaseapp.com',
    storageBucket: 'pet-care-app-2cd12.appspot.com',
    measurementId: 'G-2Z1FEGBLSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcyha72qpM_sRHBkhaAPztQF2PbmJaWA0',
    appId: '1:698815211930:android:fb7f4156b9530c9ef27223',
    messagingSenderId: '698815211930',
    projectId: 'pet-care-app-2cd12',
    storageBucket: 'pet-care-app-2cd12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNYvsrxjDXORVJKk6e736iZ4nfbqtjas',
    appId: '1:698815211930:ios:1ee91fa53d82be91f27223',
    messagingSenderId: '698815211930',
    projectId: 'pet-care-app-2cd12',
    storageBucket: 'pet-care-app-2cd12.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjNYvsrxjDXORVJKk6e736iZ4nfbqtjas',
    appId: '1:698815211930:ios:1ee91fa53d82be91f27223',
    messagingSenderId: '698815211930',
    projectId: 'pet-care-app-2cd12',
    storageBucket: 'pet-care-app-2cd12.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrB38Xp7t3UAs4d_3djLDBBmRrqdlSwtM',
    appId: '1:698815211930:web:e386b458ade68b55f27223',
    messagingSenderId: '698815211930',
    projectId: 'pet-care-app-2cd12',
    authDomain: 'pet-care-app-2cd12.firebaseapp.com',
    storageBucket: 'pet-care-app-2cd12.appspot.com',
    measurementId: 'G-WYH5SQFDT7',
  );
}
